import type { Metadata } from "next"
import { Oswald} from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider"
import { QueryProvider } from "@/providers/query-provider"
import { CurrentUserProvider } from "@/providers/user-provider"
import "./globals.css"

const oswald = Oswald({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Whey Gym | Home",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      suppressHydrationWarning
    >
      <body className={`${oswald.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <QueryProvider>
            <CurrentUserProvider>
              {children}
            </CurrentUserProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
