import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider"
import { QueryProvider } from "@/providers/query-provider"
import { CurrentUserProvider } from "@/providers/user-current-provider"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area"

const jetBrains = JetBrains_Mono({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Whey Gym | Home",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn(jetBrains.className, "antialiased h-dvh flex")}>
        <ScrollArea
          type="scroll"
          className="size-full flex flex-1"
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
          >
            <QueryProvider>
              <CurrentUserProvider>
                {children}
              </CurrentUserProvider>
            </QueryProvider>
          </ThemeProvider>
        </ScrollArea>
      </body>
    </html>
  )
}
